const prompts = [
  { text: "What are three things you are grateful for today?", index: 1 },
  { text: "Describe a positive experience you had recently.", index: 2 },
  { text: "What is something you are looking forward to?", index: 3 },
  { text: "Write about a time you overcame a challenge.", index: 4 },
  { text: "What is a personal strength you are proud of?", index: 5 },
  { text: "Who is someone who has positively impacted your life?", index: 6 },
  { text: "What is a recent accomplishment you are proud of?", index: 7 },
  { text: "Describe a place that makes you feel happy.", index: 8 },
  { text: "What is a hobby or activity that brings you joy?", index: 9 },
  { text: "Write about a time you helped someone.", index: 10 },
  { text: "What is a positive trait you admire in yourself?", index: 11 },
  { text: "What are three things you love about yourself?", index: 12 },
  { text: "Describe a happy memory from your childhood.", index: 13 },
  { text: "What is something you are proud of learning?", index: 14 },
  { text: "Who is someone you are grateful to have in your life?", index: 15 },
  { text: "What is a goal you have achieved recently?", index: 16 },
  { text: "Write about a time you felt truly at peace.", index: 17 },
  { text: "What is a positive change you have made in your life?", index: 18 },
  { text: "Describe a time when you felt proud of yourself.", index: 19 },
  { text: "What is something you love about your life?", index: 20 },
  { text: "What is a positive habit you have developed?", index: 21 },
  { text: "Write about a time you felt inspired.", index: 22 },
  { text: "What is a kind act you have done recently?", index: 23 },
  { text: "What is something you are excited about?", index: 24 },
  { text: "Describe a time when you felt truly happy.", index: 25 },
  { text: "What is a positive affirmation you can say to yourself?", index: 26 },
  { text: "What is something you appreciate about your body?", index: 27 },
  { text: "Write about a time you felt loved.", index: 28 },
  { text: "What is a positive lesson you have learned?", index: 29 },
  { text: "What is something you are proud of creating?", index: 30 },
  { text: "Describe a time when you felt confident.", index: 31 },
  { text: "What is a positive thought you had today?", index: 32 },
  { text: "What is something you are grateful for in nature?", index: 33 },
  { text: "Write about a time you felt supported.", index: 34 },
  { text: "What is a positive goal you have set for yourself?", index: 35 },
  { text: "What is something you love about your personality?", index: 36 },
  { text: "Describe a time when you felt successful.", index: 37 },
  { text: "What is a positive memory you cherish?", index: 38 },
  { text: "What is something you are proud of achieving?", index: 39 },
  { text: "Write about a time you felt truly alive.", index: 40 },
  { text: "What is a positive quality you admire in others?", index: 41 },
  { text: "What is something you are grateful for in your home?", index: 42 },
  { text: "Describe a time when you felt at peace with yourself.", index: 43 },
  { text: "What is a positive impact you have made on someone?", index: 44 },
  { text: "What is something you are proud of doing for yourself?", index: 45 },
  { text: "Write about a time you felt truly content.", index: 46 },
  { text: "What is a positive way you handle stress?", index: 47 },
  { text: "What is something you are grateful for in your community?", index: 48 },
  { text: "Describe a time when you felt truly understood.", index: 49 },
  { text: "What is a positive change you have made for your health?", index: 50 },
  { text: "What is something you are proud of accomplishing at work?", index: 51 },
  { text: "Write about a time you felt truly relaxed.", index: 52 },
  { text: "What is a positive way you show love to others?", index: 53 },
  { text: "What is something you are grateful for in your family?", index: 54 },
  { text: "Describe a time when you felt truly appreciated.", index: 55 },
  { text: "What is a positive way you handle challenges?", index: 56 },
  { text: "What is something you are proud of achieving in your personal life?", index: 57 },
  { text: "Write about a time you felt truly motivated.", index: 58 },
  { text: "What is a positive way you take care of yourself?", index: 59 },
  { text: "What is something you are grateful for in your friends?", index: 60 },
  { text: "Describe a time when you felt truly happy with your achievements.", index: 61 },
  { text: "What is a positive way you express your creativity?", index: 62 },
  { text: "What is something you are proud of learning recently?", index: 63 },
  { text: "Write about a time you felt truly connected to someone.", index: 64 },
  { text: "What is a positive way you manage your time?", index: 65 },
  { text: "What is something you are grateful for in your daily routine?", index: 66 },
  { text: "Describe a time when you felt truly proud of your efforts.", index: 67 },
  { text: "What is a positive way you handle disappointment?", index: 68 },
  { text: "What is something you are proud of achieving in your hobbies?", index: 69 },
  { text: "Write about a time you felt truly energized.", index: 70 },
  { text: "What is a positive way you show kindness to yourself?", index: 71 },
  { text: "What is something you are grateful for in your education?", index: 72 },
  { text: "Describe a time when you felt truly fulfilled.", index: 73 },
  { text: "What is a positive way you handle criticism?", index: 74 },
  { text: "What is something you are proud of achieving in your relationships?", index: 75 },
  { text: "Write about a time you felt truly optimistic.", index: 76 },
  { text: "What is a positive way you celebrate your successes?", index: 77 },
  { text: "What is something you are grateful for in your career?", index: 78 },
  { text: "Describe a time when you felt truly at ease.", index: 79 },
  { text: "What is a positive way you handle change?", index: 80 },
  { text: "What is something you are proud of achieving in your community?", index: 81 },
  { text: "Write about a time you felt truly inspired by someone.", index: 82 },
  { text: "What is a positive way you practice self-care?", index: 83 },
  { text: "What is something you are grateful for in your health?", index: 84 },
  { text: "Describe a time when you felt truly confident in your abilities.", index: 85 },
  { text: "What is a positive way you handle setbacks?", index: 86 },
  { text: "What is something you are proud of achieving in your personal growth?", index: 87 },
  { text: "Write about a time you felt truly joyful.", index: 88 },
  { text: "What is a positive way you show gratitude?", index: 89 },
  { text: "What is something you are grateful for in your leisure time?", index: 90 },
  { text: "Describe a time when you felt truly at home.", index: 91 },
  { text: "What is a positive way you handle uncertainty?", index: 92 },
  { text: "What is something you are proud of achieving in your spiritual life?", index: 93 },
  { text: "Write about a time you felt truly peaceful.", index: 94 },
  { text: "What is a positive way you nurture your relationships?", index: 95 },
  { text: "What is something you are grateful for in your surroundings?", index: 96 },
  { text: "Describe a time when you felt truly balanced.", index: 97 },
  { text: "What is a positive way you handle difficult emotions?", index: 98 },
  { text: "What is something you are proud of achieving in your mental health?", index: 99 },
  { text: "Write about a time you felt truly hopeful.", index: 100 },
  { text: "What is a positive way you start your day?", index: 101 },
  { text: "What is something you are grateful for in your morning routine?", index: 102 },
  { text: "Describe a time when you felt truly connected to nature.", index: 103 },
  { text: "What is a positive way you end your day?", index: 104 },
  { text: "What is something you are proud of achieving in your fitness?", index: 105 },
  { text: "Write about a time you felt truly refreshed.", index: 106 },
  { text: "What is a positive way you handle conflict?", index: 107 },
  { text: "What is something you are grateful for in your meals?", index: 108 },
  { text: "Describe a time when you felt truly adventurous.", index: 109 },
  { text: "What is a positive way you show empathy?", index: 110 },
  { text: "What is something you are proud of achieving in your learning?", index: 111 },
  { text: "Write about a time you felt truly creative.", index: 112 },
  { text: "What is a positive way you handle boredom?", index: 113 },
  { text: "What is something you are grateful for in your free time?", index: 114 },
  { text: "Describe a time when you felt truly spontaneous.", index: 115 },
  { text: "What is a positive way you show patience?", index: 116 },
  { text: "What is something you are proud of achieving in your projects?", index: 117 },
  { text: "Write about a time you felt truly productive.", index: 118 },
  { text: "What is a positive way you handle frustration?", index: 119 },
  { text: "What is something you are grateful for in your hobbies?", index: 120 },
  { text: "Describe a time when you felt truly curious.", index: 121 },
  { text: "What is a positive way you show resilience?", index: 122 },
  { text: "What is something you are proud of achieving in your goals?", index: 123 },
  { text: "Write about a time you felt truly determined.", index: 124 },
  { text: "What is a positive way you handle mistakes?", index: 125 },
  { text: "What is something you are grateful for in your achievements?", index: 126 },
  { text: "Describe a time when you felt truly ambitious.", index: 127 },
  { text: "What is a positive way you show courage?", index: 128 },
  { text: "What is something you are proud of achieving in your career?", index: 129 },
  { text: "Write about a time you felt truly focused.", index: 130 },
  { text: "What is a positive way you handle pressure?", index: 131 },
  { text: "What is something you are grateful for in your work?", index: 132 },
  { text: "Describe a time when you felt truly innovative.", index: 133 },
  { text: "What is a positive way you show leadership?", index: 134 },
  { text: "What is something you are proud of achieving in your team?", index: 135 },
  { text: "Write about a time you felt truly collaborative.", index: 136 },
  { text: "What is a positive way you handle deadlines?", index: 137 },
  { text: "What is something you are grateful for in your colleagues?", index: 138 },
  { text: "Describe a time when you felt truly resourceful.", index: 139 },
  { text: "What is a positive way you show initiative?", index: 140 },
  { text: "What is something you are proud of achieving in your projects?", index: 141 },
  { text: "Write about a time you felt truly strategic.", index: 142 },
  { text: "What is a positive way you handle feedback?", index: 143 },
  { text: "What is something you are grateful for in your mentors?", index: 144 },
  { text: "Describe a time when you felt truly insightful.", index: 145 },
  { text: "What is a positive way you show gratitude?", index: 146 },
  { text: "What is something you are proud of achieving in your personal development?", index: 147 },
  { text: "Write about a time you felt truly reflective.", index: 148 },
  { text: "What is a positive way you handle setbacks?", index: 149 },
  { text: "What is something you are grateful for in your growth?", index: 150 },
  { text: "Describe a time when you felt truly enlightened.", index: 151 },
  { text: "What is a positive way you show mindfulness?", index: 152 },
  { text: "What is something you are proud of achieving in your mindfulness practice?", index: 153 },
  { text: "Write about a time you felt truly present.", index: 154 },
  { text: "What is a positive way you handle distractions?", index: 155 },
  { text: "What is something you are grateful for in your meditation?", index: 156 },
  { text: "Describe a time when you felt truly centered.", index: 157 },
  { text: "What is a positive way you show self-awareness?", index: 158 },
  { text: "What is something you are proud of achieving in your self-awareness?", index: 159 },
  { text: "Write about a time you felt truly introspective.", index: 160 },
  { text: "What is a positive way you handle self-doubt?", index: 161 },
  { text: "What is something you are grateful for in your self-reflection?", index: 162 },
  { text: "Describe a time when you felt truly self-assured.", index: 163 },
  { text: "What is a positive way you show self-compassion?", index: 164 },
  { text: "What is something you are proud of achieving in your self-compassion?", index: 165 },
  { text: "Write about a time you felt truly self-loving.", index: 166 },
  { text: "What is a positive way you handle self-criticism?", index: 167 },
  { text: "What is something you are grateful for in your self-care?", index: 168 },
  { text: "Describe a time when you felt truly self-accepting.", index: 169 },
  { text: "What is a positive way you show self-respect?", index: 170 },
  { text: "What is something you are proud of achieving in your self-respect?", index: 171 },
  { text: "Write about a time you felt truly self-confident.", index: 172 },
  { text: "What is a positive way you handle self-improvement?", index: 173 },
  { text: "What is something you are grateful for in your self-growth?", index: 174 },
  { text: "Describe a time when you felt truly self-empowered.", index: 175 },
  { text: "What is a positive way you show self-discipline?", index: 176 },
  { text: "What is something you are proud of achieving in your self-discipline?", index: 177 },
  { text: "Write about a time you felt truly self-motivated.", index: 178 },
  { text: "What is a positive way you handle self-control?", index: 179 },
  { text: "What is something you are grateful for in your self-regulation?", index: 180 },
  { text: "Describe a time when you felt truly self-directed.", index: 181 },
  { text: "What is a positive way you show self-reliance?", index: 182 },
  { text: "What is something you are proud of achieving in your self-reliance?", index: 183 },
  { text: "Write about a time you felt truly self-sufficient.", index: 184 },
  { text: "What is a positive way you handle self-management?", index: 185 },
  { text: "What is something you are grateful for in your self-leadership?", index: 186 },
  { text: "Describe a time when you felt truly self-governed.", index: 187 },
  { text: "What is a positive way you show self-determination?", index: 188 },
  { text: "What is something you are proud of achieving in your self-determination?", index: 189 },
  { text: "Write about a time you felt truly self-driven.", index: 190 },
  { text: "What is a positive way you handle self-mastery?", index: 191 },
  { text: "What is something you are grateful for in your self-actualization?", index: 192 },
  { text: "Describe a time when you felt truly self-fulfilled.", index: 193 },
  { text: "What is a positive way you show self-acceptance?", index: 194 },
  { text: "What is something you are proud of achieving in your self-acceptance?", index: 195 },
  { text: "Write about a time you felt truly self-content.", index: 196 },
  { text: "What is a positive way you handle self-awareness?", index: 197 },
  { text: "What is something you are grateful for in your self-awareness?", index: 198 },
  { text: "Describe a time when you felt truly self-aware.", index: 199 },
  { text: "What is a positive way you show self-love?", index: 200 },
  { text: "What is a positive way you handle anxiety?", index: 201 },
  { text: "What is something you are grateful for in your mental clarity?", index: 202 },
  { text: "Describe a time when you felt truly mentally strong.", index: 203 },
  { text: "What is a positive way you show mental resilience?", index: 204 },
  { text: "What is something you are proud of achieving in your mental resilience?", index: 205 },
  { text: "Write about a time you felt truly mentally balanced.", index: 206 },
  { text: "What is a positive way you handle mental fatigue?", index: 207 },
  { text: "What is something you are grateful for in your mental stamina?", index: 208 },
  { text: "Describe a time when you felt truly mentally refreshed.", index: 209 },
  { text: "What is a positive way you show mental agility?", index: 210 },
  { text: "What is something you are proud of achieving in your mental agility?", index: 211 },
  { text: "Write about a time you felt truly mentally sharp.", index: 212 },
  { text: "What is a positive way you handle mental challenges?", index: 213 },
  { text: "What is something you are grateful for in your mental health?", index: 214 },
  { text: "Describe a time when you felt truly mentally at peace.", index: 215 },
  { text: "What is a positive way you show mental fortitude?", index: 216 },
  { text: "What is something you are proud of achieving in your mental fortitude?", index: 217 },
  { text: "Write about a time you felt truly mentally resilient.", index: 218 },
  { text: "What is a positive way you handle mental stress?", index: 219 },
  { text: "What is something you are grateful for in your mental well-being?", index: 220 },
  { text: "Describe a time when you felt truly mentally clear.", index: 221 },
  { text: "What is a positive way you show mental strength?", index: 222 },
  { text: "What is something you are proud of achieving in your mental strength?", index: 223 },
  { text: "Write about a time you felt truly mentally focused.", index: 224 },
  { text: "What is a positive way you handle mental pressure?", index: 225 },
  { text: "What is something you are grateful for in your mental focus?", index: 226 },
  { text: "Describe a time when you felt truly mentally prepared.", index: 227 },
  { text: "What is a positive way you show mental preparedness?", index: 228 },
  { text: "What is something you are proud of achieving in your mental preparedness?", index: 229 },
  { text: "Write about a time you felt truly mentally disciplined.", index: 230 },
  { text: "What is a positive way you handle mental obstacles?", index: 231 },
  { text: "What is something you are grateful for in your mental discipline?", index: 232 },
  { text: "Describe a time when you felt truly mentally capable.", index: 233 },
  { text: "What is a positive way you show mental capability?", index: 234 },
  { text: "What is something you are proud of achieving in your mental capability?", index: 235 },
  { text: "Write about a time you felt truly mentally adept.", index: 236 },
  { text: "What is a positive way you handle mental adversity?", index: 237 },
  { text: "What is something you are grateful for in your mental adaptability?", index: 238 },
  { text: "Describe a time when you felt truly mentally adaptable.", index: 239 },
  { text: "What is a positive way you show mental adaptability?", index: 240 },
  { text: "What is something you are proud of achieving in your mental adaptability?", index: 241 },
  { text: "Write about a time you felt truly mentally flexible.", index: 242 },
  { text: "What is a positive way you handle mental rigidity?", index: 243 },
  { text: "What is something you are grateful for in your mental flexibility?", index: 244 },
  { text: "Describe a time when you felt truly mentally versatile.", index: 245 },
  { text: "What is a positive way you show mental versatility?", index: 246 },
  { text: "What is something you are proud of achieving in your mental versatility?", index: 247 },
  { text: "Write about a time you felt truly mentally innovative.", index: 248 },
  { text: "What is a positive way you handle mental stagnation?", index: 249 },
  { text: "What is something you are grateful for in your mental creativity?", index: 250 },
  { text: "Describe a time when you felt truly mentally creative.", index: 251 },
  { text: "What is a positive way you show mental creativity?", index: 252 },
  { text: "What is something you are proud of achieving in your mental creativity?", index: 253 },
  { text: "Write about a time you felt truly mentally imaginative.", index: 254 },
  { text: "What is a positive way you handle mental blocks?", index: 255 },
  { text: "What is something you are grateful for in your mental innovation?", index: 256 },
  { text: "Describe a time when you felt truly mentally inventive.", index: 257 },
  { text: "What is a positive way you show mental inventiveness?", index: 258 },
  { text: "What is something you are proud of achieving in your mental inventiveness?", index: 259 },
  { text: "Write about a time you felt truly mentally resourceful.", index: 260 },
  { text: "What is a positive way you handle mental exhaustion?", index: 261 },
  { text: "What is something you are grateful for in your mental endurance?", index: 262 },
  { text: "Describe a time when you felt truly mentally enduring.", index: 263 },
  { text: "What is a positive way you show mental endurance?", index: 264 },
  { text: "What is something you are proud of achieving in your mental endurance?", index: 265 },
  { text: "Write about a time you felt truly mentally persistent.", index: 266 },
  { text: "What is a positive way you handle mental persistence?", index: 267 },
  { text: "What is something you are grateful for in your mental persistence?", index: 268 },
  { text: "Describe a time when you felt truly mentally tenacious.", index: 269 },
  { text: "What is a positive way you show mental tenacity?", index: 270 },
  { text: "What is something you are proud of achieving in your mental tenacity?", index: 271 },
  { text: "Write about a time you felt truly mentally determined.", index: 272 },
  { text: "What is a positive way you handle mental determination?", index: 273 },
  { text: "What is something you are grateful for in your mental determination?", index: 274 },
  { text: "Describe a time when you felt truly mentally resolute.", index: 275 },
  { text: "What is a positive way you show mental resolution?", index: 276 },
  { text: "What is something you are proud of achieving in your mental resolution?", index: 277 },
  { text: "Write about a time you felt truly mentally unwavering.", index: 278 },
  { text: "What is a positive way you handle mental steadfastness?", index: 279 },
  { text: "What is something you are grateful for in your mental steadfastness?", index: 280 },
  { text: "Describe a time when you felt truly mentally steadfast.", index: 281 },
  { text: "What is a positive way you show mental steadfastness?", index: 282 },
  { text: "What is something you are proud of achieving in your mental steadfastness?", index: 283 },
  { text: "Write about a time you felt truly mentally unyielding.", index: 284 },
  { text: "What is a positive way you handle mental fortitude?", index: 285 },
  { text: "What is something you are grateful for in your mental fortitude?", index: 286 },
  { text: "Describe a time when you felt truly mentally fortified.", index: 287 },
  { text: "What is a positive way you show mental fortification?", index: 288 },
  { text: "What is something you are proud of achieving in your mental fortification?", index: 289 },
  { text: "Write about a time you felt truly mentally robust.", index: 290 },
  { text: "What is a positive way you handle mental robustness?", index: 291 },
  { text: "What is something you are grateful for in your mental robustness?", index: 292 },
  { text: "Describe a time when you felt truly mentally vigorous.", index: 293 },
  { text: "What is a positive way you show mental vigor?", index: 294 },
  { text: "What is something you are proud of achieving in your mental vigor?", index: 295 },
  { text: "Write about a time you felt truly mentally energetic.", index: 296 },
  { text: "What is a positive way you handle mental energy?", index: 297 },
  { text: "What is something you are grateful for in your mental energy?", index: 298 },
  { text: "Describe a time when you felt truly mentally dynamic.", index: 299 },
  { text: "What is a positive way you show mental dynamism?", index: 300 },
  { text: "What is something you are proud of achieving in your mental dynamism?", index: 301 },
  { text: "Write about a time you felt truly mentally agile.", index: 302 },
  { text: "What is a positive way you handle mental agility?", index: 303 },
  { text: "What is something you are grateful for in your mental agility?", index: 304 },
  { text: "Describe a time when you felt truly mentally flexible.", index: 305 },
  { text: "What is a positive way you show mental flexibility?", index: 306 },
  { text: "What is something you are proud of achieving in your mental flexibility?", index: 307 },
  { text: "Write about a time you felt truly mentally adaptable.", index: 308 },
  { text: "What is a positive way you handle mental adaptability?", index: 309 },
  { text: "What is something you are grateful for in your mental adaptability?", index: 310 },
  { text: "Describe a time when you felt truly mentally versatile.", index: 311 },
  { text: "What is a positive way you show mental versatility?", index: 312 },
  { text: "What is something you are proud of achieving in your mental versatility?", index: 313 },
  { text: "Write about a time you felt truly mentally innovative.", index: 314 },
  { text: "What is a positive way you handle mental innovation?", index: 315 },
  { text: "What is something you are grateful for in your mental innovation?", index: 316 },
  { text: "Describe a time when you felt truly mentally creative.", index: 317 },
  { text: "What is a positive way you show mental creativity?", index: 318 },
  { text: "What is something you are proud of achieving in your mental creativity?", index: 319 },
  { text: "Write about a time you felt truly mentally imaginative.", index: 320 },
  { text: "What is a positive way you handle mental imagination?", index: 321 },
  { text: "What is something you are grateful for in your mental imagination?", index: 322 },
  { text: "Describe a time when you felt truly mentally inventive.", index: 323 },
  { text: "What is a positive way you show mental inventiveness?", index: 324 },
  { text: "What is something you are proud of achieving in your mental inventiveness?", index: 325 },
  { text: "Write about a time you felt truly mentally resourceful.", index: 326 },
  { text: "What is a positive way you handle mental resourcefulness?", index: 327 },
  { text: "What is something you are grateful for in your mental resourcefulness?", index: 328 },
  { text: "Describe a time when you felt truly mentally enduring.", index: 329 },
  { text: "What is a positive way you show mental endurance?", index: 330 },
  { text: "What is something you are proud of achieving in your mental endurance?", index: 331 },
  { text: "Write about a time you felt truly mentally persistent.", index: 332 },
  { text: "What is a positive way you handle mental persistence?", index: 333 },
  { text: "What is something you are grateful for in your mental persistence?", index: 334 },
  { text: "Describe a time when you felt truly mentally tenacious.", index: 335 },
  { text: "What is a positive way you show mental tenacity?", index: 336 },
  { text: "What is something you are proud of achieving in your mental tenacity?", index: 337 },
  { text: "Write about a time you felt truly mentally determined.", index: 338 },
  { text: "What is a positive way you handle mental determination?", index: 339 },
  { text: "What is something you are grateful for in your mental determination?", index: 340 },
  { text: "Describe a time when you felt truly mentally resolute.", index: 341 },
  { text: "What is a positive way you show mental resolution?", index: 342 },
  { text: "What is something you are proud of achieving in your mental resolution?", index: 343 },
  { text: "Write about a time you felt truly mentally unwavering.", index: 344 },
  { text: "What is a positive way you handle mental steadfastness?", index: 345 },
  { text: "What is something you are grateful for in your mental steadfastness?", index: 346 },
  { text: "Describe a time when you felt truly mentally steadfast.", index: 347 },
  { text: "What is a positive way you show mental steadfastness?", index: 348 },
  { text: "What is something you are proud of achieving in your mental steadfastness?", index: 349 },
  { text: "Write about a time you felt truly mentally unyielding.", index: 350 },
  { text: "What is a positive way you handle mental fortitude?", index: 351 },
  { text: "What is something you are grateful for in your mental fortitude?", index: 352 },
  { text: "Describe a time when you felt truly mentally fortified.", index: 353 },
  { text: "What is a positive way you show mental fortification?", index: 354 },
  { text: "What is something you are proud of achieving in your mental fortification?", index: 355 },
  { text: "Write about a time you felt truly mentally robust.", index: 356 },
  { text: "What is a positive way you handle mental robustness?", index: 357 },
  { text: "What is something you are grateful for in your mental robustness?", index: 358 },
  { text: "Describe a time when you felt truly mentally vigorous.", index: 359 },
  { text: "What is a positive way you show mental vigor?", index: 360 },
  { text: "What is something you are proud of achieving in your mental vigor?", index: 361 },
  { text: "Write about a time you felt truly mentally energetic.", index: 362 },
  { text: "What is a positive way you handle mental energy?", index: 363 },
  { text: "What is something you are grateful for in your mental energy?", index: 364 },
  { text: "Describe a time when you felt truly mentally dynamic.", index: 365 },
  { text: "What is a positive way you show mental dynamism?", index: 366 },
  { text: "What is something you are proud of achieving in your mental dynamism?", index: 367 },
  { text: "Write about a time you felt truly mentally agile.", index: 368 },
  { text: "What is a positive way you handle mental agility?", index: 369 },
  { text: "What is something you are grateful for in your mental agility?", index: 370 },
  { text: "Describe a time when you felt truly mentally flexible.", index: 371 },
  { text: "What is a positive way you show mental flexibility?", index: 372 },
  { text: "What is something you are proud of achieving in your mental flexibility?", index: 373 },
  { text: "Write about a time you felt truly mentally adaptable.", index: 374 },
  { text: "What is a positive way you handle mental adaptability?", index: 375 },
  { text: "What is something you are grateful for in your mental adaptability?", index: 376 },
  { text: "Describe a time when you felt truly mentally versatile.", index: 377 },
  { text: "What is a positive way you show mental versatility?", index: 378 },
  { text: "What is something you are proud of achieving in your mental versatility?", index: 379 },
  { text: "Write about a time you felt truly mentally innovative.", index: 380 },
  { text: "What is a positive way you handle mental innovation?", index: 381 },
  { text: "What is something you are grateful for in your mental innovation?", index: 382 },
  { text: "Describe a time when you felt truly mentally creative.", index: 383 },
  { text: "What is a positive way you show mental creativity?", index: 384 },
  { text: "What is something you are proud of achieving in your mental creativity?", index: 385 },
  { text: "Write about a time you felt truly mentally imaginative.", index: 386 },
  { text: "What is a positive way you handle mental imagination?", index: 387 },
  { text: "What is something you are grateful for in your mental imagination?", index: 388 },
  { text: "Describe a time when you felt truly mentally inventive.", index: 389 },
  { text: "What is a positive way you show mental inventiveness?", index: 390 },
  { text: "What is something you are proud of achieving in your mental inventiveness?", index: 391 },
  { text: "Write about a time you felt truly mentally resourceful.", index: 392 },
  { text: "What is a positive way you handle mental resourcefulness?", index: 393 },
  { text: "What is something you are grateful for in your mental resourcefulness?", index: 394 },
  { text: "Describe a time when you felt truly mentally enduring.", index: 395 },
  { text: "What is a positive way you show mental endurance?", index: 396 },
  { text: "What is something you are proud of achieving in your mental endurance?", index: 397 },
  { text: "Write about a time you felt truly mentally persistent.", index: 398 },
  { text: "What is a positive way you handle mental persistence?", index: 399 },
  { text: "What is something you are grateful for in your mental persistence?", index: 400 }
];

const uniquePrompts = Array.from(new Set(prompts.map(prompt => prompt.text)))
  .map(text => prompts.find(prompt => prompt.text === text));

console.log(uniquePrompts);

export default prompts;