export const positivePrompts = [
  { text: "What are three things you appreciate about your intelligence?", index: 1, topic: "positive" },
  { text: "Describe a positive experience you had recently.", index: 2, topic: "positive" },
  { text: "What is something you are looking forward to?", index: 3, topic: "positive" },
  { text: "Write about a time you overcame a challenge.", index: 4, topic: "positive" },
  { text: "What is a personal strength you are proud of?", index: 5, topic: "positive" },
  { text: "Who is someone who has positively impacted your life?", index: 6, topic: "positive" },
  { text: "What is a recent accomplishment you are proud of?", index: 7, topic: "positive" },
  { text: "Describe a place that makes you feel happy.", index: 8, topic: "positive" },
  { text: "What is a hobby or activity that brings you joy?", index: 9, topic: "positive" },
  { text: "Write about a time you helped someone.", index: 10, topic: "positive" },
  { text: "What is a positive trait you admire in yourself?", index: 11, topic: "positive" },
  { text: "What are three things you love about yourself?", index: 12, topic: "positive" },
  { text: "Describe a happy memory from your childhood.", index: 13, topic: "positive" },
  { text: "What is something you are proud of learning?", index: 14, topic: "positive" },
  { text: "Who is someone you are grateful to have in your life?", index: 15, topic: "positive" },
  { text: "What is a goal you have achieved recently?", index: 16, topic: "positive" },
  { text: "Write about a time you felt truly at peace.", index: 17, topic: "positive" },
  { text: "What is a positive change you have made in your life?", index: 18, topic: "positive" },
  { text: "Describe a time when you felt proud of yourself.", index: 19, topic: "positive" },
  { text: "What is something you love about your life?", index: 20, topic: "positive" },
  { text: "What is a positive habit you have developed?", index: 21, topic: "positive" },
  { text: "Write about a time you felt inspired.", index: 22, topic: "positive" },
  { text: "What is a kind act you have done recently?", index: 23, topic: "positive" },
  { text: "What is something you are excited about?", index: 24, topic: "positive" },
  { text: "Describe a time when you felt truly happy.", index: 25, topic: "positive" },
  { text: "What is a positive affirmation you can say to yourself?", index: 26, topic: "positive" },
  { text: "What is something you appreciate about your body?", index: 27, topic: "positive" },
  { text: "Write about a time you felt loved.", index: 28, topic: "positive" },
  { text: "What is a positive lesson you have learned?", index: 29, topic: "positive" },
  { text: "What is something you are proud of creating?", index: 30, topic: "positive" },
  { text: "Describe a time when you felt confident.", index: 31, topic: "positive" },
  { text: "What is a positive thought you had today?", index: 32, topic: "positive" },
  { text: "What is something you are grateful for in nature?", index: 33, topic: "positive" },
  { text: "Write about a time you felt supported.", index: 34, topic: "positive" },
  { text: "What is a positive goal you have set for yourself?", index: 35, topic: "positive" },
  { text: "What is something you love about your personality?", index: 36, topic: "positive" },
  { text: "Describe a time when you felt successful.", index: 37, topic: "positive" },
  { text: "What is a positive memory you cherish?", index: 38, topic: "positive" },
  { text: "What is something you are proud of achieving?", index: 39, topic: "positive" },
  { text: "Write about a time you felt truly alive.", index: 40, topic: "positive" },
  { text: "Describe something special or exceptional about yourself.", index: 41, topic: "positive" },
  { text: "What is something you are grateful for in your dwelling?", index: 42, topic: "positive" },
  { text: "Describe a time when you felt at peace with yourself.", index: 43, topic: "positive" },
  { text: "What is a positive impact you have made on someone?", index: 44, topic: "positive" },
  { text: "What is something you are proud of doing for yourself?", index: 45, topic: "positive" },
  { text: "Write about a time you felt truly content.", index: 46, topic: "positive" },
  { text: "What is a positive way you handle stress?", index: 47, topic: "positive" },
  { text: "What is something you are grateful for in your community?", index: 48, topic: "positive" },
  { text: "Describe a time when you felt truly understood.", index: 49, topic: "positive" },
  { text: "What is a positive change you have made for your health?", index: 50, topic: "positive" },
  { text: "What is something you are proud of accomplishing at work?", index: 51, topic: "positive" },
  { text: "Write about a time you felt truly relaxed.", index: 52, topic: "positive" },
  { text: "What is a positive way you show love to others?", index: 53, topic: "positive" },
  { text: "What is something you are grateful for in your family?", index: 54, topic: "positive" },
  { text: "Describe a time when you felt truly appreciated.", index: 55, topic: "positive" },
  { text: "What is a positive way you handle challenges?", index: 56, topic: "positive" },
  { text: "What is something you are proud of achieving in your personal life?", index: 57, topic: "positive" },
  { text: "Write about a time you felt truly motivated.", index: 58, topic: "positive" },
  { text: "What is a positive way you take care of yourself?", index: 59, topic: "positive" },
  { text: "What is something you are grateful for in your friends?", index: 60, topic: "positive" },
  { text: "Describe a time when you felt truly happy with your achievements.", index: 61, topic: "positive" },
  { text: "What is a positive way you express your creativity?", index: 62, topic: "positive" },
  { text: "What is something you are proud of learning recently?", index: 63, topic: "positive" },
  { text: "Write about a time you felt truly connected to someone.", index: 64, topic: "positive" },
  { text: "What is a positive way you manage your time?", index: 65, topic: "positive" },
  { text: "What is something you are grateful for in your daily routine?", index: 66, topic: "positive" },
  { text: "Describe a time when you felt truly proud of your efforts.", index: 67, topic: "positive" },
  { text: "What is a positive way you handle disappointment?", index: 68, topic: "positive" },
  { text: "What is something you are proud of achieving in your hobbies?", index: 69, topic: "positive" },
  { text: "Write about a time you felt truly energized.", index: 70, topic: "positive" },
  { text: "What is a positive way you show kindness to yourself?", index: 71, topic: "positive" },
  { text: "What is something you are grateful for in your education?", index: 72, topic: "positive" },
  { text: "Describe a time when you felt truly fulfilled.", index: 73, topic: "positive" },
  { text: "What is a positive way you handle criticism?", index: 74, topic: "positive" },
  { text: "What is something you are proud of achieving in your relationships?", index: 75, topic: "positive" },
  { text: "Write about a time you felt truly optimistic.", index: 76, topic: "positive" },
  { text: "What is a positive way you celebrate your successes?", index: 77, topic: "positive" },
  { text: "What is something you are grateful for in your career?", index: 78, topic: "positive" },
  { text: "Describe a time when you felt truly at ease.", index: 79, topic: "positive" },
  { text: "What is a positive way you handle change?", index: 80, topic: "positive" },
  { text: "What is something you are proud of achieving in your community?", index: 81, topic: "positive" },
  { text: "Write about a time you felt truly inspired by someone.", index: 82, topic: "positive" },
  { text: "What is a positive way you practice self-care?", index: 83, topic: "positive" },
  { text: "What is something you are grateful for in your health?", index: 84, topic: "positive" },
  { text: "Describe a time when you felt truly confident in your abilities.", index: 85, topic: "positive" },
  { text: "What is a positive way you handle setbacks?", index: 86, topic: "positive" },
  { text: "What is something you are proud of achieving in your personal growth?", index: 87, topic: "positive" },
  { text: "Write about a time you felt truly joyful.", index: 88, topic: "positive" },
  { text: "What is a positive way you show gratitude?", index: 89, topic: "positive" },
  { text: "What is something you are grateful for in your leisure time?", index: 90, topic: "positive" },
  { text: "Describe a time when you felt truly at home.", index: 91, topic: "positive" },
  { text: "What is a positive way you handle uncertainty?", index: 92, topic: "positive" },
  { text: "What is something you are proud of achieving in your spiritual life?", index: 93, topic: "positive" },
  { text: "Write about a time you felt truly peaceful.", index: 94, topic: "positive" },
  { text: "What is a positive way you nurture your relationships?", index: 95, topic: "positive" },
  { text: "What is something you are grateful for in your surroundings?", index: 96, topic: "positive" },
  { text: "Describe a time when you felt truly balanced.", index: 97, topic: "positive" },
  { text: "What is a positive way you handle difficult emotions?", index: 98, topic: "positive" },
  { text: "What is something you are proud of achieving in your mental health?", index: 99, topic: "positive" },
  { text: "Write about a time you felt truly hopeful.", index: 100, topic: "positive" }
];